# Generated by Django 2.2 on 2021-06-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival_radio_api', '0004_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistitem',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='spotify_token',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
